sonar.organization=bagasdhitya
sonar.projectKey=BagasDhitya_jcwdjkt-modul-5
sonar.projectName=jcwdjkt-modul-5
sonar.projectVersion=1.0

sonar.modules=frontend,backend

# Konfigurasi untuk frontend
frontend.sonar.projectName=My Blog
frontend.sonar.projectBaseDir=my-blog
frontend.sonar.sources=app

# Untuk mengabaikan node_modules, next, dan dist
frontend.sonar.exclusions=node_modules/**, .next/**, dist/**

# Konfigurasi untuk backend
backend.sonar.projectName=My Blog Api
backend.sonar.projectBaseDir=my-blog-api
backend.sonar.sources=src
backend.sonar.exclusions=node_modules/**, dist/**, prisma/**