name: CI Pipeline

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.5.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
          cache-dependency-path: my-blog-api/package-lock.json

      - name: Install dependencies
        run: |
          cd my-blog-api
          npm ci

      - name: Generate Prisma Client
        run: |
          cd my-blog-api
          npx prisma generate

      - name: Run Tests
        run: |
          cd my-blog-api
          npx jest --config jest.config.ts

      - name: Discord Notification
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            COLOR=2664261
          else
            COLOR=14431557
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "CI Pipeline Build Status",
                   "description": "Repository: ${{ github.repository }}\nCommit: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.actor }}",
                   "color": '$COLOR'
                 }]
               }' \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Prepare Email Template Assets
        if: always()
        run: |
          # 1. Set parameter warna tema status
          if [ "${{ job.status }}" = "success" ]; then
            echo "STATUS_COLOR=#34d399" >> $GITHUB_ENV
            echo "BORDER_COLOR=#059669" >> $GITHUB_ENV
          else
            echo "STATUS_COLOR=#f87171" >> $GITHUB_ENV
            echo "BORDER_COLOR=#dc2626" >> $GITHUB_ENV
          fi

          # 2. Map data GitHub ke env biasa untuk disubstitusi ke HTML tanpa merusak YAML
          export JOB_STATUS="${{ job.status }}"
          export REPO_NAME="${{ github.repository }}"
          export BRANCH_NAME="${{ github.ref_name }}"
          export ACTOR_NAME="${{ github.actor }}"
          export COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          export RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # 3. Inject value env ke dalam template file HTML
          envsubst < .github/email-template.html > .github/ready-email.html

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[Github Actions] ${{ github.repository }} - Build ${{ job.status }}"
          to: ${{ secrets.NOTIF_EMAIL_RECEIVER }}
          from: Github Actions Runner <${{ secrets.SMTP_USER }}>
          html_body: file://.github/ready-email.html
