name: CI Pipeline

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.5.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
          cache-dependency-path: my-blog-api/package-lock.json

      - name: Install dependencies
        run: |
          cd my-blog-api
          npm ci

      - name: Generate Prisma Client
        run: |
          cd my-blog-api
          npx prisma generate

      - name: Run Tests
        run: |
          cd my-blog-api
          npx jest --config jest.config.ts

      - name: Discord Notification
        if: always()
        run: |
          # Tentukan warna berdasarkan status job (Green untuk sukses, Red untuk gagal)
          if [ "${{ job.status }}" = "success" ]; then
            COLOR=2664261  # Desimal dari #28A745
          else
            COLOR=14431557 # Desimal dari #DC3545
          fi

          # Kirim payload JSON ke Discord menggunakan cURL
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "CI Pipeline Build Status",
                   "description": "Repository: ${{ github.repository }}\nCommit: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.actor }}",
                   "color": '$COLOR'
                 }]
               }' \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[Github Actions] ${{ github.repository }} - Build ${{ job.status }}"
          to: ${{ secrets.NOTIF_EMAIL_RECEIVER }}
          from: Github Actions Runner <${{ secrets.SMTP_USER }}>
          body: |
            GitHub Actions Build Status: ${{ job.status }}

            Project   : ${{ github.repository }}
            Branch    : ${{ github.ref_name }}
            Commit    : ${{ github.event.head_commit.message }}
            Triggered By : ${{ github.actor }}

            Link ke Workflow Run:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
